from langchain_core.messages import SystemMessage

from app.agent.instructions import (
    AGENT_IDENTITY,
    CORE_BOUNDARIES,
    SAFETY_GUARDRAILS,
    SAFE_RESPONSE_BEHAVIOR,
    EDUCATION_BOUNDARIES,
    RECOMMENDATION_BOUNDARIES,
    RESPONSE_CONTROLS,
    UNCERTAINTY_AND_CLARIFICATION,
    SCOPE_BOUNDARIES,
)



SYSTEM_PROMPT = f"""
{AGENT_IDENTITY}

{CORE_BOUNDARIES}

{SAFETY_GUARDRAILS}

{SAFE_RESPONSE_BEHAVIOR}

{SCOPE_BOUNDARIES}

{EDUCATION_BOUNDARIES}

{RECOMMENDATION_BOUNDARIES}

{RESPONSE_CONTROLS}

{UNCERTAINTY_AND_CLARIFICATION}
"""


def get_system_message():
    return SystemMessage(content=SYSTEM_PROMPT)
